CREATE TABLE IF NOT EXISTS alignment_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  driver_type TEXT,
  driven_type TEXT,
  driver_name TEXT,
  driven_name TEXT,
  project_name TEXT,
  equipment_tag TEXT,
  location TEXT,
  customer_name TEXT,
  alignment_date TEXT,
  technician_name TEXT,
  alignment_method TEXT DEFAULT 'laser',
  before_data JSONB DEFAULT '{}'::jsonb,
  after_data JSONB DEFAULT '{}'::jsonb,
  tolerance_offset_max NUMERIC DEFAULT 0.05,
  tolerance_angle_max NUMERIC DEFAULT 0.03,
  angular_tolerance NUMERIC DEFAULT 0.03,
  offset_tolerance NUMERIC DEFAULT 0.05,
  service_remarks TEXT,
  recommendations TEXT,
  approved_by TEXT,
  customer_acknowledgment TEXT,
  rpm NUMERIC DEFAULT 0,
  coupling_type TEXT,
  shim_added TEXT
);
